[package]
name = "ytkit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]
name = "ytkit"

[workspace]
members = ["common", "innertube", "youtube"]

[workspace.dependencies]
anyhow = "1.0.100"
jsonpath-rust = "1.0.4"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.221", features = ["derive"] }
serde_json = "1.0.145"
serde_with = "3.15.0"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.16"
time = { version = "0.3.44", features = ["serde-human-readable"] }
tokio = { version = "1.47.1", features = ["full"] }
uniffi = { version = "0.29", features = ["tokio"] }

[dependencies]
common = { path = "common" }
innertube = { path = "innertube" }
youtube = { path = "youtube" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
uniffi.workspace = true

[dev-dependencies]
tokio.workspace = true
